Implement Basic Data Structures using Numpy, Pandas
1. Lists
2. Arrays
3. Identify their type using type()

In [10]:
import numpy as np
l1=[1,2,3,4,5]
l2=[6,7,8,9,5]
array1=np.array(l1)
array2=np.array(l2)
print(l1)
print(l2)
print(array1)
print(array2)
type(array1)
type(array2)







[1, 2, 3, 4, 5]
[6, 7, 8, 9, 5]
[1 2 3 4 5]
[6 7 8 9 5]


numpy.ndarray

mathematical operations on lists


In [13]:
multiply=np.multiply(l1,l2)
divide=np.divide(l2,l1)
power=np.power(l1,l2)
print(multiply)
print(divide)
print(power)


[ 6 14 24 36 25]
[6.         3.5        2.66666667 2.25       1.        ]
[     1    128   6561 262144   3125]


mathematical operations on arrays

In [14]:
multiply_array=np.multiply(array1,array2)
divide_array=np.divide(array2,array1)
power_array=np.power(array1,array2)
print(multiply_array)
print(divide_array)
print(power_array)

[ 6 14 24 36 25]
[6.         3.5        2.66666667 2.25       1.        ]
[     1    128   6561 262144   3125]


Combine text with Numpy fuction to generate a textual output - "Addition of Two:
array1 +array 2

In [26]:
import numpy as np
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result_array = array1 + array2
text_output = f"Addition of Two:\narray1 + array2\n{array1} + {array2} = {result_array}"
print(text_output)





Addition of Two:
array1 + array2
[1 2 3] + [4 5 6] = [5 7 9]


Implement np.sin(), log(), log2(), np.exp()

In [17]:
sin_values = np.sin(array1)
log_values = np.log(array2)
log2_values = np.log2(array1)
exp_values = np.exp(array2)


print("sin(array1):", sin_values)
print("log(array2):", log_values)
print("log2(array1):", log2_values)
print("exp(array2):", exp_values)

sin(array1): [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
log(array2): [1.79175947 1.94591015 2.07944154 2.19722458 1.60943791]
log2(array1): [0.         1.         1.5849625  2.         2.32192809]
exp(array2): [ 403.42879349 1096.63315843 2980.95798704 8103.08392758  148.4131591 ]
